// Mock data store for Checked By (QC Reviewer) role.

class QCDataStore {
  static final QCDataStore instance = QCDataStore._internal();
  QCDataStore._internal();

  final List<Map<String, dynamic>> reports = [
    {
      'id': 'MSR-2026-9001',
      'title': 'Lashing & Measurement Survey',
      'type': 'Lashing & Measurement',
      'vessel': 'Ever Given',
      'client': 'Evergreen Line',
      'date': '10 Jul 2026',
      'submittedDate': '10 Jul 2026',
      'dueDate': '12 Jul 2026',
      'priority': 'High',
      'status': 'Pending Verification', // Pending Verification, Under Review, Returned, Verified, Submitted
      'preparedBy': 'Sarah Preparer',
      'surveyBy': 'Field Surveyor John',
      'location': 'JNPT Terminal 2',
      'instructions': 'Ensure all wire ropes are verified. Verify payload weight matching.',
      'exporter': 'India Steel Export Co',
      'consignee': 'Europe Cargo Hub',
      'shippingLine': 'Evergreen Marine',
      'billNo': 'SB-1002019',
      'billDate': '09 Jul 2026',
      'invoiceNo': 'INV-9902A',
      'invoiceDate': '09 Jul 2026',
      'description': 'Heavy Machinery parts & Steel sheets',
      'grossWeight': 42.1,
      'quantity': 18,
      'discharge': 'Rotterdam',
      'containerNo': 'EMCU-992019-3',
      'containerSize': '40ft HC',
      'stuffPkg': 18,
      'cargoWeight': 39.7,
      'tareWeight': 2.4,
      'totalWeight': 42.1,
      'payload': 30.4,
      'acep': 'ACEP-IN-88',
      'csc': 'CSC-11029',
      'condition': 'Excellent',
      'obsFieldObservations': 'Cargo properly secured on wooden blocks.',
      'obsLashingVerification': 'All turnbuckles tensioned and secured.',
      'obsMeasurementVerification': 'Overall dimensions: 11.8m x 2.3m x 2.6m.',
      'obsRemarks': 'Safe for ocean transit.',
      'photos': <Map<String, dynamic>>[
        {
          'id': 'p1',
          'category': 'Front View',
          'caption': 'Container Front Face',
          'metadata': '10 Jul 2026, 11:30 AM | GPS: 18.9504, 72.8258 | Device: CAT S62 Pro',
          'remarks': 'Clear view of locking rods.',
          'isVerified': false,
          'isRejected': false,
        },
        {
          'id': 'p2',
          'category': 'Lashing Details',
          'caption': 'Double Turnbuckles',
          'metadata': '10 Jul 2026, 11:32 AM | GPS: 18.9504, 72.8258 | Device: CAT S62 Pro',
          'remarks': 'Lashing tension seems tight.',
          'isVerified': false,
          'isRejected': false,
        }
      ],
      'documents': <Map<String, dynamic>>[
        {
          'name': 'Container_Packing_List.pdf',
          'size': '850 KB',
          'isVerified': false,
          'isRejected': false,
        },
        {
          'name': 'Weight_Bridge_Receipt.pdf',
          'size': '1.1 MB',
          'isVerified': false,
          'isRejected': false,
        }
      ],
      'generalRemarks': '',
      'qcNotes': '',
      'verifiedSections': <String, bool>{
        'Client Info': false,
        'Vessel Info': false,
        'Cargo Info': false,
        'Survey Details': false,
        'Measurements': false,
        'Lashing Details': false,
        'Damage Details': false,
        'Remarks': false,
        'Documents': false,
        'Photos': false,
      },
      'activities': [
        {'time': '10 Jul 2026, 10:00 AM', 'title': 'Report Completed', 'desc': 'Surveyor John submitted on-site details.'}
      ],
      'returnReason': '',
      'returnTarget': '', // Prepared By, Survey By
    },
    {
      'id': 'MSR-2026-9002',
      'title': 'ODC Survey Report',
      'type': 'ODC Survey',
      'vessel': 'Pacific Star',
      'client': 'Apex Logistics',
      'date': '09 Jul 2026',
      'submittedDate': '09 Jul 2026',
      'dueDate': '11 Jul 2026',
      'priority': 'Medium',
      'status': 'Under Review',
      'preparedBy': 'Sarah Preparer',
      'surveyBy': 'Field Surveyor John',
      'location': 'JNPT Terminal 1',
      'instructions': 'Conduct ODC check for over-height cargo.',
      'exporter': 'BHEL Ltd',
      'consignee': 'Jebel Ali Power',
      'shippingLine': 'COSCO',
      'billNo': 'SB-110299',
      'billDate': '08 Jul 2026',
      'invoiceNo': 'INV-402C',
      'invoiceDate': '08 Jul 2026',
      'description': 'Industrial Boiler Unit',
      'grossWeight': 55.4,
      'quantity': 1,
      'discharge': 'Jebel Ali',
      'obsOdcVerification': 'Pre-verification shows 15cm height limit violation.',
      'obsCargoPositioning': 'Center-loaded on flatrack.',
      'obsSafetyObservations': 'Securing wire ropes have double clamps.',
      'obsRemarks': 'Boiler is safely secured.',
      'photos': <Map<String, dynamic>>[
        {
          'id': 'p3',
          'category': 'Overall View',
          'caption': 'Boiler Flatrack View',
          'metadata': '09 Jul 2026, 02:40 PM | GPS: 18.9504, 72.8258 | Device: CAT S62 Pro',
          'remarks': 'Boiler centers match guidelines.',
          'isVerified': true,
          'isRejected': false,
        }
      ],
      'documents': <Map<String, dynamic>>[],
      'generalRemarks': 'Initial verification looks correct.',
      'qcNotes': 'Awaiting final signature check.',
      'verifiedSections': <String, bool>{
        'Client Info': true,
        'Vessel Info': true,
        'Cargo Info': true,
        'Survey Details': true,
        'Measurements': false,
        'Lashing Details': false,
        'Damage Details': false,
        'Remarks': false,
        'Documents': false,
        'Photos': true,
      },
      'activities': [
        {'time': '09 Jul 2026, 04:00 PM', 'title': 'Review Started', 'desc': 'QC reviewer began verification.'}
      ],
      'returnReason': '',
      'returnTarget': '',
    },
    {
      'id': 'MSR-2026-9003',
      'title': 'Container Damage Survey',
      'type': 'Container Damage',
      'vessel': 'Ever Star',
      'client': 'Evergreen Line',
      'date': '08 Jul 2026',
      'submittedDate': '08 Jul 2026',
      'dueDate': '10 Jul 2026',
      'priority': 'High',
      'status': 'Returned',
      'preparedBy': 'Sarah Preparer',
      'surveyBy': 'Field Surveyor John',
      'location': 'JNPT Terminal 1',
      'instructions': 'Check top casting structural damage.',
      'exporter': 'Global Metal Co',
      'consignee': 'Euro Scrap Ltd',
      'shippingLine': 'Evergreen',
      'billNo': 'SB-881902',
      'billDate': '07 Jul 2026',
      'invoiceNo': 'INV-1102A',
      'invoiceDate': '07 Jul 2026',
      'description': 'Industrial Scrap Metal',
      'grossWeight': 26.5,
      'quantity': 3,
      'discharge': 'Hamburg',
      'obsDamageVerification': 'Top-left corner casting sheared and cracked.',
      'obsDamageLocation': 'Top corner, bay 14.',
      'obsDamageObservations': 'Rust and shear fracture marks.',
      'obsConditionRemarks': 'Reject container for sea voyage until casting is replaced.',
      'photos': <Map<String, dynamic>>[
        {
          'id': 'p4',
          'category': 'Damage Close-up',
          'caption': 'Casting Crack',
          'metadata': '08 Jul 2026, 09:15 AM | GPS: 18.9504, 72.8258 | Device: CAT S62 Pro',
          'remarks': 'Close up of sheared corner.',
          'isVerified': false,
          'isRejected': true,
        }
      ],
      'documents': <Map<String, dynamic>>[],
      'generalRemarks': 'Casting integrity is critical. Photo uploaded has poor clarity.',
      'qcNotes': 'Returned to Surveyor for high resolution corner photos.',
      'verifiedSections': <String, bool>{
        'Client Info': true,
        'Vessel Info': true,
        'Cargo Info': true,
        'Survey Details': true,
        'Measurements': false,
        'Lashing Details': false,
        'Damage Details': false,
        'Remarks': false,
        'Documents': false,
        'Photos': false,
      },
      'activities': [
        {'time': '08 Jul 2026, 11:00 AM', 'title': 'QC Review Returned', 'desc': 'Returned to Survey By: Upload higher resolution photo of casting crack.'}
      ],
      'returnReason': 'Upload higher resolution photo of casting crack.',
      'returnTarget': 'Survey By',
    },
    {
      'id': 'MSR-2026-9004',
      'title': 'Lashing & Measurement Survey',
      'type': 'Lashing & Measurement',
      'vessel': 'COSCO Oceania',
      'client': 'COSCO Line',
      'date': '07 Jul 2026',
      'submittedDate': '07 Jul 2026',
      'dueDate': '09 Jul 2026',
      'priority': 'Medium',
      'status': 'Submitted',
      'preparedBy': 'Sarah Preparer',
      'surveyBy': 'Field Surveyor John',
      'location': 'Port of Mumbai - Berth 14',
      'instructions': 'Ensure double turnbuckle lashing checks.',
      'exporter': 'Tata Heavy Eng',
      'consignee': 'Dubai Port Trust',
      'shippingLine': 'COSCO',
      'billNo': 'SB-901122',
      'billDate': '06 Jul 2026',
      'invoiceNo': 'INV-4091A',
      'invoiceDate': '06 Jul 2026',
      'description': 'Commercial Heavy Trucks',
      'grossWeight': 38.2,
      'quantity': 6,
      'discharge': 'Jebel Ali',
      'obsFieldObservations': 'All trucks chained and wood chocks nailed.',
      'obsLashingVerification': 'All tension keys locked.',
      'obsMeasurementVerification': 'Dimensions verified.',
      'obsRemarks': 'Ready.',
      'photos': <Map<String, dynamic>>[],
      'documents': <Map<String, dynamic>>[],
      'generalRemarks': 'Boiler is safely secured.',
      'qcNotes': 'Review completed and submitted to Company Admin.',
      'verifiedSections': <String, bool>{
        'Client Info': true,
        'Vessel Info': true,
        'Cargo Info': true,
        'Survey Details': true,
        'Measurements': true,
        'Lashing Details': true,
        'Damage Details': true,
        'Remarks': true,
        'Documents': true,
        'Photos': true,
      },
      'activities': [
        {'time': '07 Jul 2026, 02:00 PM', 'title': 'QC Verified', 'desc': 'Verified by Checked By Marc.'},
        {'time': '07 Jul 2026, 03:00 PM', 'title': 'Submitted to Admin', 'desc': 'Report forwarded to Company Admin.'}
      ],
      'returnReason': '',
      'returnTarget': '',
    }
  ];

  final List<Map<String, String>> notifications = [
    {
      'title': 'New Survey Submitted',
      'time': '12 mins ago',
      'desc': 'Lashing & Measurement (MSR-2026-9001) has been submitted by Surveyor John. Ready for QC verification.',
      'isNew': 'true',
    },
    {
      'title': 'Report Corrected & Updated',
      'time': '3 hours ago',
      'desc': 'Container Damage (MSR-2026-9003) has been updated by Surveyor John after correction review request.',
      'isNew': 'true',
    }
  ];

  void addNotification(String title, String desc) {
    notifications.insert(0, {
      'title': title,
      'time': 'Just now',
      'desc': desc,
      'isNew': 'true',
    });
  }
}
